name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet WebAPI
      run: dotnet build ./SmallAnalytics.WebAPI/SmallAnalytics.WebAPI.csproj --configuration Release
    - name: Test with dotnet
      run: dotnet test ./SmallAnalytics.Tests
